;;;; models.lisp --- the Model family, against a real CNA runtime.
;;;;
;;;; Five levels of evidence, kept apart on purpose, because "Model works" is not
;;;; a claim anything here makes:
;;;;
;;;;   STRUCTURAL   symbols, classes, hierarchy -- tests/structure/, not here
;;;;   XNA_BEHAVIOR the IL's validation, transforms and identity semantics
;;;;   NATIVE       CNA handles, routes and lifetimes
;;;;   CONTENT      Load<Model>, the cache and Unload
;;;;   SOFTWARE     geometry that actually reaches pixels -- rasterization.lisp
;;;;
;;;; The fixture is `tests/fixtures/three-bone-triangles.cnj' and its two binary
;;;; sidecars, generated by `tools/qualification/make-model-fixture.py'. Two bones
;;;; in a hierarchy, two meshes on different bones, one part each, geometry
;;;; already in clip space. The child bone's transform carries a **scale** as well
;;;; as a translation, which is what makes the multiplication order observable:
;;;; with pure translations `local * parent' and `parent * local' agree.

(in-package #:cna-common-lisp.tests)
(in-suite native-tests)

(defparameter *model-asset* "three-bone-triangles")

(defun model-loading-available-p ()
  "Whether this CNA can offer `Load<Model>' at all.

**Not a skip: a branch, and both branches are asserted.** On CNA 0.21.0
`cna_model_destroy' on a content-loaded model is a null dereference, so the
loader refuses there rather than handing a program a call that kills the process.
On 0.22.0 it works. Every test below that needs a loaded model asserts the
refusal when it cannot have one, exactly as the rasterization tests assert the
no-readback branch -- a lane that silently skipped would stop proving anything on
the ABI it skipped."
  (not (eql (int:loaded-abi-version) (int:encode-abi-version 0 21 0))))

(defun %assert-model-loading-refused (game)
  "The 0.21.0 branch: the loader refused, said why, and left the game usable."
  (let ((condition (model-load-error game)))
    (is (typep condition 'xna:cna-not-supported-error)
        "Load<Model> should refuse on this ABI; it signalled ~a" (type-of condition))
    (when condition
      (is (search "cna_model_destroy" (princ-to-string condition))
          "the refusal must name the defect it is standing in for")
      (is (search "0.22.0" (princ-to-string condition))
          "and the version that does not have it"))
    (is (null (loaded-model game)) "and it must not have produced a model")))

(defclass model-game (graphics-game)
  ((model :initform nil :accessor loaded-model)
   (second-model :initform nil :accessor second-loaded-model)
   (own-effect :initform nil :accessor own-effect)
   (load-error :initform nil :accessor model-load-error)
   (probe :initarg :probe :initform nil :accessor model-probe)
   (probe-result :initform nil :accessor model-probe-result))
  (:documentation "Loads the model fixture through the game's own ContentManager."))

(defun %model-content-root ()
  (let ((path (truename (fixture-path "three-bone-triangles.cnj"))))
    (namestring (make-pathname :name nil :type nil :defaults path))))

(defmethod xna:load-content ((game model-game))
  (call-next-method)
  (handler-case
      (let ((content (xna:content game)))
        (setf (xna.content:root-directory content) (%model-content-root))
        (setf (loaded-model game)
              (xna.content:load-asset content 'gfx:model *model-asset*))
        ;; An ordinary BasicEffect, made the way a program makes one -- which is
        ;; the remedy the content-published refusal names, so the fixture has one
        ;; ready rather than each test building it.
        (setf (own-effect game)
              (make-instance 'gfx:basic-effect :graphics-device (xna:graphics-device game)))
        (let ((probe (model-probe game)))
          (when probe (setf (model-probe-result game) (funcall probe game)))))
    (error (condition) (setf (model-load-error game) condition))))

(defun %tear-down-model-game (game)
  "Give everything back in CNA's required order, then the game.

**Leaving one child alive strands the game for every later test**, because CNA
allows one active game per process and DISPOSE refuses while a child lives. That
is what this exists for: GRAPHICS-GAME owns a batch and a texture, this fixture
owns a BasicEffect, and the content manager owns the model."
  (ignore-errors (xna.content:unload (xna:content game)))
  (when (own-effect game) (ignore-errors (xna:dispose (own-effect game))))
  (when (batch game) (ignore-errors (xna:dispose (batch game))))
  (when (texture game) (ignore-errors (xna:dispose (texture game))))
  (when (manager game) (ignore-errors (xna:dispose (manager game))))
  (ignore-errors (xna:dispose game))
  (xna:disposed-p game))

(defmacro with-model-game ((variable &rest initargs) &body body)
  "Run one frame of a MODEL-GAME and assert with the model still alive."
  `(let ((,variable (make-instance 'model-game ,@initargs)))
     (unwind-protect
          (progn (xna:run-one-frame ,variable)
                 (if (model-loading-available-p)
                     (progn
                       (is (null (model-load-error ,variable))
                           "loading the model fixture failed: ~a"
                           (model-load-error ,variable))
                       ,@body)
                     (%assert-model-loading-refused ,variable)))
       ;; Unload is what disposes a loaded model, exactly as it disposes a loaded
       ;; font: Model is not IDisposable in XNA and the handle still has to go back.
       (is (%tear-down-model-game ,variable)
           "the model game did not shut down, which strands it for every later test"))))

;;; --- CONTENT: the producer, the cache and Unload ----------------------------

(define-native-test a-model-loads-through-the-content-manager
  "`ContentManager.Load<Model>', which is the only public producer XNA has.

The fixture's whole shape in one assertion set: two bones, two meshes, one part
per mesh, and the names the `.cnj' declares."
  (with-model-game (game)
    (let ((model (loaded-model game)))
      (is (typep model 'gfx:model))
      (is (= 3 (gfx:collection-count (gfx:model-bones model))))
      (is (= 2 (gfx:collection-count (gfx:model-meshes model))))
      (is (equal '("Root" "Arm" "Hand")
                 (mapcar #'gfx:model-bone-name
                         (gfx:collection-elements (gfx:model-bones model)))))
      (is (equal '("LeftTriangle" "RightTriangle")
                 (mapcar #'gfx:model-mesh-name
                         (gfx:collection-elements (gfx:model-meshes model)))))
      (dolist (mesh (gfx:collection-elements (gfx:model-meshes model)))
        (is (= 1 (gfx:collection-count (gfx:model-mesh-parts mesh)))
            "~a should have exactly one part" (gfx:model-mesh-name mesh))))))

(define-native-test loading-one-model-twice-answers-one-object
  "XNA's `Load<T>' looks the cleaned name up in `loadedAssets' before reading
anything, whatever T is, so two loads of one name answer one object.

CNA's own route caches too, but re-publishing answers a **new model handle** over
the same native model -- which would be two objects for one name and two graphs
to keep in step. The managed cache is what a program sees, as it is for every
other loader here."
  (with-model-game (game :probe (lambda (game)
                                  (xna.content:load-asset
                                   (xna:content game) 'gfx:model *model-asset*)))
    (is (eq (loaded-model game) (model-probe-result game))
        "the second Load<Model> answered a different object")))

(define-native-test unload-disposes-a-loaded-model-and-its-views-refuse-afterwards
  "What becomes invalid after `ContentManager.Unload', and how it refuses.

A ModelBone is not IDisposable in XNA and neither is a Model, so nothing here
gets a Dispose of its own -- but every one of them holds a CNA handle the model
released, and a live-looking object over a released handle is the thing this
must not leave behind. Each refuses by name."
  (let ((game (make-instance 'model-game)))
    (unwind-protect
         (when (model-loading-available-p)
           (xna:run-one-frame game)
           (is (null (model-load-error game)))
           (let* ((model (loaded-model game))
                  (bone (gfx:collection-item (gfx:model-bones model) 0))
                  (mesh (gfx:collection-item (gfx:model-meshes model) 0))
                  (part (gfx:collection-item (gfx:model-mesh-parts mesh) 0)))
             (xna.content:unload (xna:content game))
             (is (xna:disposed-p model) "Unload must dispose what it loaded")
             (signals xna:cna-error (gfx:model-bones model))
             (signals xna:cna-error (gfx:model-bone-name bone))
             (signals xna:cna-error (gfx:model-mesh-name mesh))
             (signals xna:cna-error (gfx:model-mesh-part-num-vertices part))))
      (is (%tear-down-model-game game)
          "and the game shuts down, which it could not if a handle had been kept"))))

;;; --- XNA_BEHAVIOR: identity ------------------------------------------------

(define-native-test the-model-graph-answers-one-object-per-bone
  "**CNA handle identity is not XNA object identity, and this is the test that
says so.** `CreateBoneHandle' makes a new registry handle on every call, so
`cna_model_bone_collection_get_at(bones, 0)' twice answers two handles for one
bone. XNA's `Bones[0]' twice answers one object, and every cross-reference --
a parent, a child, a mesh's parent bone, the root -- is that same object.

A binding that wrapped each handle as it came would pass every count assertion
in this file and fail every EQ one."
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (bones (gfx:model-bones model))
           (root (gfx:collection-item bones 0))
           (arm (gfx:collection-item bones 1))
           (hand (gfx:collection-item bones 2)))
      (is (eq root (gfx:collection-item bones 0))
          "two reads of Bones[0] must answer one object")
      (is (eq bones (gfx:model-bones model))
          "and Bones itself is a field, so it is the same collection object")
      (is (eq root (gfx:model-root model)) "Root is Bones[0], not a copy of it")
      (is (eq root (gfx:model-bone-parent arm))
          "arm.Parent must be the parent *object*")
      (is (eq arm (gfx:model-bone-parent hand)) "and the hierarchy is two deep")
      (is (eq arm (gfx:collection-item (gfx:model-bone-children root) 0))
          "and parent.Children[0] must be the child object")
      (is (eq hand (gfx:collection-item (gfx:model-bone-children arm) 0)))
      (is (null (gfx:model-bone-parent root)) "the root has no parent")
      (is (= 0 (gfx:collection-count (gfx:model-bone-children hand))))
      (let ((meshes (gfx:model-meshes model)))
        (is (eq arm (gfx:model-mesh-parent-bone (gfx:collection-item meshes 0))))
        (is (eq hand (gfx:model-mesh-parent-bone (gfx:collection-item meshes 1)))
            "the two meshes hang off different bones, which is what makes the
             absolute-transform test mean anything")))))

(define-native-test bone-indices-are-the-positions-the-graph-is-expressed-in
  (with-model-game (game)
    (let ((bones (gfx:collection-elements (gfx:model-bones (loaded-model game)))))
      (loop for bone in bones
            for position from 0
            do (is (= position (gfx:model-bone-index bone))
                   "Bones[~d].Index answered ~d" position (gfx:model-bone-index bone))))))

;;; --- XNA_BEHAVIOR: the three transform operations ---------------------------

(defun %translation-of (matrix)
  (list (xna:matrix-m41 matrix) (xna:matrix-m42 matrix) (xna:matrix-m43 matrix)))

(define-native-test local-bone-transforms-are-what-the-fixture-declares
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (locals (make-array 3)))
      (gfx:copy-bone-transforms-to model locals)
      (is (equal '(0.0 0.0 0.0) (%translation-of (aref locals 0)))
          "**the root's declared transform does not survive CNA's reader**, which
           is measured rather than assumed: a two-bone version of this fixture put
           the translation on entry 0 and read it back as identity. The fixture
           puts the interesting pair one level down for that reason")
      (is (equal '(10.0 0.0 0.0) (%translation-of (aref locals 1)))
          "the arm's local translation is the fixture's (10, 0, 0)")
      (is (equal '(0.0 5.0 0.0) (%translation-of (aref locals 2)))
          "and the hand's is (0, 5, 0)")
      (is (= 2.0 (xna:matrix-m11 (aref locals 2)))
          "the hand also scales by two, which is what makes the order observable")
      (is (equalp (gfx:model-bone-transform (gfx:collection-item (gfx:model-bones model) 1))
                  (aref locals 1))
          "and the bulk copy agrees with the per-bone reader"))))

(define-native-test absolute-bone-transforms-compose-in-xnas-order
  "`absolute[i] = local[i] * absolute[parent.Index]', local on the **left**.

This is the whole content of the member, and the fixture is built so that the
wrong order gives a different number: the child scales by two and translates by
(0, 5, 0) over a root that translates by (10, 0, 0).

    local * parent  ->  translation (10, 5, 0)     <- XNA's, and this
    parent * local  ->  translation (20, 5, 0)

A pure-translation fixture cannot tell those apart, which is why this one is not
one."
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (absolute (make-array 3)))
      (gfx:copy-absolute-bone-transforms-to model absolute)
      (is (equal '(0.0 0.0 0.0) (%translation-of (aref absolute 0)))
          "a root's absolute transform is its local one")
      (is (equal '(10.0 0.0 0.0) (%translation-of (aref absolute 1)))
          "and a child of the root composes with an identity")
      (is (equal '(10.0 5.0 0.0) (%translation-of (aref absolute 2)))
          "the hand's is local * parent; (20, 5, 0) would be the reverse order")
      (is (= 2.0 (xna:matrix-m11 (aref absolute 2)))
          "and the scale survives the composition"))))

(define-native-test cna-and-this-binding-agree-about-absolute-bone-transforms
  "Both sides pinned, for the reason the graphics state objects pin both.

The arithmetic above is this binding's, transcribed from the IL rather than taken
from `cna_model_copy_absolute_bone_transforms'. Asserting that CNA's route agrees
is what makes that a measurement: a CNA that changed fails here rather than
silently changing this binding's public answer."
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (mine (make-array 3)))
      (gfx:copy-absolute-bone-transforms-to model mine)
      (cffi:with-foreign-object (buffer '(:struct cna-lisp.internal.ffi::cna-matrix) 3)
        (cffi:with-foreign-object (out :uint64)
          (is (zerop (cna-lisp.internal.ffi::%model-copy-absolute-bone-transforms
                      (int:handle-of model) buffer 3 out))))
        (dotimes (index 3)
          (is (equalp (aref mine index)
                      (microsoft.xna.framework.graphics::%read-matrix
                       (cffi:mem-aptr buffer '(:struct cna-lisp.internal.ffi::cna-matrix)
                                      index)))
              "bone ~d: CNA and this binding disagree about the absolute transform"
              index))))))

(define-native-test copy-bone-transforms-from-writes-every-bone
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (hand (gfx:collection-item (gfx:model-bones model) 2))
           (replacement (vector (xna:matrix-create-translation 1.0 2.0 3.0)
                                (xna:matrix-create-translation 4.0 5.0 6.0)
                                (xna:matrix-create-translation 7.0 8.0 9.0)))
           (readback (make-array 3)))
      (gfx:copy-bone-transforms-from model replacement)
      (gfx:copy-bone-transforms-to model readback)
      (is (equal '(1.0 2.0 3.0) (%translation-of (aref readback 0))))
      (is (equal '(4.0 5.0 6.0) (%translation-of (aref readback 1))))
      (is (equal '(7.0 8.0 9.0) (%translation-of (gfx:model-bone-transform hand)))
          "and the per-bone reader sees it too")
      ;; The absolute transforms follow, which is the point of writing them.
      (let ((absolute (make-array 3)))
        (gfx:copy-absolute-bone-transforms-to model absolute)
        (is (equal '(12.0 15.0 18.0) (%translation-of (aref absolute 2)))
            "three translations compose by adding, whichever order they multiply in")))))

(define-native-test setting-one-bones-transform-leaves-the-others-alone
  "`ModelBone.Transform''s setter is one `stfld' in XNA.

It is written here through the model's bulk route, because the bone's own route
takes CNA_Matrix by value. That is the same value written the same way, and this
is what says so: one bone changes and the other does not."
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (bones (gfx:model-bones model))
           (root (gfx:collection-item bones 0))
           (hand (gfx:collection-item bones 2))
           (before (gfx:model-bone-transform root)))
      (setf (gfx:model-bone-transform hand) (xna:matrix-create-translation 7.0 8.0 9.0))
      (is (equal '(7.0 8.0 9.0) (%translation-of (gfx:model-bone-transform hand))))
      (is (equalp before (gfx:model-bone-transform root))
          "the root's transform must not have moved"))))

(define-native-test the-transform-copies-validate-exactly-what-the-il-validates
  "Null first, then a destination shorter than Bones.Count, and a longer one is
accepted -- which is what `Model.Draw' relies on, since it reuses one array."
  (with-model-game (game)
    (let ((model (loaded-model game)))
      (dolist (operation (list #'gfx:copy-bone-transforms-to
                               #'gfx:copy-absolute-bone-transforms-to
                               #'gfx:copy-bone-transforms-from))
        (signals xna:cna-argument-error (funcall operation model nil))
        (signals xna:cna-argument-out-of-range-error
          (funcall operation model (make-array 1))))
      (finishes (gfx:copy-bone-transforms-to model (make-array 5)))
      (finishes (gfx:copy-absolute-bone-transforms-to model (make-array 5))))))

;;; --- XNA_BEHAVIOR: the collections -----------------------------------------

(define-native-test a-model-collections-indexer-answers-and-refuses-as-xnas-does
  "**Not the effect collections' contract, and that is read out of the IL.**
`ModelBoneCollection.get_Item(string)' calls TryGetValue and, when it answers
false, does `newobj KeyNotFoundException; throw'. The effect collections' answer
null for a miss; assuming these did the same is exactly the mistake this pins."
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (bones (gfx:model-bones model))
           (meshes (gfx:model-meshes model)))
      (is (eq (gfx:collection-item bones 1) (gfx:collection-item bones "Arm")))
      (is (eq (gfx:collection-item meshes 1) (gfx:collection-item meshes "RightTriangle")))
      ;; A miss throws rather than answering NIL.
      (signals xna:cna-invalid-argument-error (gfx:collection-item bones "NoSuchBone"))
      (signals xna:cna-invalid-argument-error (gfx:collection-item meshes "NoSuchMesh"))
      ;; Ordinal comparison, so case matters.
      (signals xna:cna-invalid-argument-error (gfx:collection-item bones "root"))
      ;; The integer indexer is ReadOnlyCollection<T>'s and throws out of range.
      (signals xna:cna-argument-out-of-range-error (gfx:collection-item bones -1))
      (signals xna:cna-argument-out-of-range-error (gfx:collection-item bones 3))
      ;; TryGetValue answers two values, and null or empty is an argument error.
      (multiple-value-bind (bone found) (gfx:collection-try-get-value bones "Hand")
        (is (eq t (not (null found))))
        (is (eq bone (gfx:collection-item bones 2))))
      (multiple-value-bind (bone found) (gfx:collection-try-get-value bones "NoSuchBone")
        (is (null found))
        (is (null bone) "a miss assigns null, as the IL's `stind.ref' of null does"))
      (signals xna:cna-argument-error (gfx:collection-try-get-value bones ""))
      (signals xna:cna-argument-error (gfx:collection-try-get-value bones nil)))))

(define-native-test a-model-collections-enumerator-is-a-cursor
  "`GetEnumerator()' answers XNA's own nested type, positioned before the first
element. COLLECTION-ELEMENTS is what a Lisp program iterates; both exist."
  (with-model-game (game)
    (let* ((bones (gfx:model-bones (loaded-model game)))
           (cursor (gfx:collection-enumerator bones)))
      (is (typep cursor 'gfx:model-bone-collection-enumerator))
      (signals xna:cna-invalid-state-error (gfx:enumerator-current cursor))
      (is (eq t (gfx:enumerator-move-next cursor)))
      (is (eq (gfx:collection-item bones 0) (gfx:enumerator-current cursor)))
      (is (eq t (gfx:enumerator-move-next cursor)))
      (is (eq (gfx:collection-item bones 1) (gfx:enumerator-current cursor)))
      (is (eq t (gfx:enumerator-move-next cursor)))
      (is (eq (gfx:collection-item bones 2) (gfx:enumerator-current cursor)))
      (is (null (gfx:enumerator-move-next cursor)))
      (is (null (gfx:enumerator-move-next cursor))
          "past the end it keeps answering false rather than running away")
      (signals xna:cna-invalid-state-error (gfx:enumerator-current cursor))
      (finishes (xna:dispose cursor))
      ;; And the list projection agrees with the cursor, in order.
      (is (equal (gfx:collection-elements bones)
                 (list (gfx:collection-item bones 0) (gfx:collection-item bones 1)
                       (gfx:collection-item bones 2)))))))

;;; --- XNA_BEHAVIOR: Tag ------------------------------------------------------

(define-native-test tag-keeps-the-lisp-object-a-program-put-in-it
  "XNA's Tag is `System.Object' and CNA's is a uint64 token, which could only
hold a *pointer* to a Lisp object -- the thing this binding never puts into C.
So the tag is a managed slot, and that is also the only projection under which
this assertion can hold at all."
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (mesh (gfx:collection-item (gfx:model-meshes model) 0))
           (part (gfx:collection-item (gfx:model-mesh-parts mesh) 0))
           (payload (list :arbitrary "lisp" #(1 2 3))))
      (dolist (object (list model mesh part))
        (is (null (gfx:tag object)) "an unset Tag is NIL, as XNA's is null")
        (setf (gfx:tag object) payload)
        (is (eq payload (gfx:tag object))
            "~a's Tag must answer the very object it was given" (type-of object))))))

;;; --- NATIVE: the parts, their buffers and their effects ---------------------

(define-native-test a-mesh-part-reports-the-geometry-the-fixture-declares
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (meshes (gfx:collection-elements (gfx:model-meshes model))))
      (loop for mesh in meshes
            for part = (gfx:collection-item (gfx:model-mesh-parts mesh) 0)
            do (is (= 3 (gfx:model-mesh-part-num-vertices part))
                   "~a: three vertices" (gfx:model-mesh-name mesh))
               (is (= 1 (gfx:model-mesh-part-primitive-count part))
                   "~a: one triangle" (gfx:model-mesh-name mesh))
               (is (= 0 (gfx:model-mesh-part-start-index part))
                   "each mesh has its own index file, so each starts at zero")
               (is (= 0 (gfx:model-mesh-part-vertex-offset part)))
               (is (typep (gfx:model-mesh-part-vertex-buffer part) 'gfx:vertex-buffer))
               (is (typep (gfx:model-mesh-part-index-buffer part) 'gfx:index-buffer))))))

(define-native-test a-model-owned-buffer-is-an-ordinary-buffer-the-caller-may-not-dispose
  "Not a model-only wrapper type: `ModelMeshPart.VertexBuffer' is a VertexBuffer,
with the declaration CNA holds for it rebuilt from the elements rather than
invented. It is `:PARENT-OWNED', so DISPOSE refuses and says to dispose the
parent -- which is the truth twice over, because the handle is the model's and
CNA would refuse the destroy as well."
  (with-model-game (game)
    (let* ((mesh (gfx:collection-item (gfx:model-meshes (loaded-model game)) 0))
           (part (gfx:collection-item (gfx:model-mesh-parts mesh) 0))
           (buffer (gfx:model-mesh-part-vertex-buffer part)))
      (is (= 3 (gfx:vertex-count buffer)) "one triangle's three vertices")
      (is (= 16 (gfx:vertex-stride (gfx:vertex-declaration buffer)))
          "and the stride the .cnj declares")
      (is (plusp (length (gfx:get-vertex-elements (gfx:vertex-declaration buffer))))
          "with a real element layout read back from CNA")
      (signals xna:cna-ownership-error (xna:dispose buffer))
      (is (not (xna:disposed-p buffer)) "a refused disposal must leave it usable")
      (is (eq buffer (gfx:model-mesh-part-vertex-buffer part))
          "and it is the same object every time"))))

(define-native-test one-native-effect-answers-one-clos-object
  "CNA's loader publishes one handle per **distinct** native effect -- its
`published' map is keyed on the object address, deliberately -- and this binding
maps a handle to the one object for it. So handle identity is a faithful key
here, unlike for bones, where every read makes a new handle.

**Measured, not assumed: this fixture's two meshes get two effects**, because
CNA's `.cnj` reader builds one BasicEffect per mesh entry. So what is asserted is
the mapping, in both directions: a mesh's Effects[0] is its part's effect object,
two reads of one part's effect answer one object, and the two meshes' effects are
distinct because the native ones are."
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (meshes (gfx:collection-elements (gfx:model-meshes model)))
           (parts (mapcar (lambda (mesh) (gfx:collection-item (gfx:model-mesh-parts mesh) 0))
                          meshes))
           (effects (mapcar #'gfx:model-mesh-part-effect parts)))
      (dolist (effect effects) (is (typep effect 'gfx:basic-effect)))
      (is (eq (first effects) (gfx:model-mesh-part-effect (first parts)))
          "two reads of one part's effect must answer one object")
      (is (not (eq (first effects) (second effects)))
          "and two native effects must not collapse onto one object")
      (loop for mesh in meshes
            for effect in effects
            do (is (= 1 (gfx:collection-count (gfx:model-mesh-effects mesh)))
                   "a mesh whose one part has one effect lists it once")
               (is (eq effect (gfx:collection-item (gfx:model-mesh-effects mesh) 0))
                   "and Effects[0] is that same object")))))

(define-native-test one-effect-on-two-parts-is-listed-once
  "`ModelMesh.Effects' is a **deduplicated set** of its parts' effects, and this
is where that is proved rather than inferred from a fixture that happens to have
one part per mesh: both meshes' parts are given the same effect object, and each
mesh still lists exactly one."
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (meshes (gfx:collection-elements (gfx:model-meshes model)))
           (parts (mapcar (lambda (mesh) (gfx:collection-item (gfx:model-mesh-parts mesh) 0))
                          meshes))
           (mine (own-effect game)))
      (dolist (part parts) (setf (gfx:model-mesh-part-effect part) mine))
      (dolist (part parts) (is (eq mine (gfx:model-mesh-part-effect part))))
      (loop for mesh in meshes
            do (is (= 1 (gfx:collection-count (gfx:model-mesh-effects mesh)))
                   "~a lists one effect, not two" (gfx:model-mesh-name mesh))
               (is (eq mine (gfx:collection-item (gfx:model-mesh-effects mesh) 0))))
      ;; And clearing one takes it out again.
      (setf (gfx:model-mesh-part-effect (first parts)) nil)
      (is (null (gfx:model-mesh-part-effect (first parts))))
      (is (= 0 (gfx:collection-count (gfx:model-mesh-effects (first meshes))))
          "no part of that mesh uses an effect any more, so it lists none"))))

(define-native-test a-content-published-effect-refuses-its-graph-and-says-why
  "**The measured CNA defect, pinned so a fixed CNA fails this test.**

`cna_content_manager_load_model' publishes a loaded model's effect handle with no
`adapterState'; `GetEffectState' casts that null pointer, so
`cna_effect_get_techniques' on such a handle is a memory fault at offset 0x20
rather than a result code -- on 0.21.0, 0.22.0 and 0.23.0 alike. A binding cannot
contain a segfault, so it refuses before reaching the route.

**The refusal used to cover four members and the unsafe set is seventeen.**
`tools/qualification/model-defect-matrix.sh' enumerates the routes that read
`adapterState' straight out of CNA's own source -- 22 of the 322 in
`CnaCApiEffects.cpp' -- and 17 of them are bound here. Four were guarded. The
other thirteen are the stock effects' `Texture' pairs, `DualTextureEffect''s two
layers, `EnvironmentMapEffect.EnvironmentMap' and
`cna_effect_lights_get_directional_light', and the first two of those were
measured killing a subprocess at address 0x0 on 0.22.0 and 0.23.0 through
`BasicEffect.Texture' -- an ordinary XNA member, on the class a `.cnj' model
actually publishes. This test is now the whole audited set.

What it asserts is both halves: every member that would read the missing state
refuses, by name, and the ones that do not read it answer normally. If CNA is
fixed, the refusals become wrong and this test is where that is noticed."
  (with-model-game (game)
    (let* ((mesh (gfx:collection-item (gfx:model-meshes (loaded-model game)) 0))
           (part (gfx:collection-item (gfx:model-mesh-parts mesh) 0))
           (effect (gfx:model-mesh-part-effect part)))
      ;; The four graph entry points.
      (signals xna:cna-not-supported-error (gfx:effect-techniques effect))
      (signals xna:cna-not-supported-error (gfx:effect-current-technique effect))
      (signals xna:cna-not-supported-error (gfx:effect-parameters effect))
      (signals xna:cna-not-supported-error (gfx:clone-effect effect))
      ;; The texture pair, which is what a program actually reaches for. The
      ;; fixture publishes a BasicEffect, so these are the routes measured
      ;; faulting at 0x0 in a subprocess.
      (signals xna:cna-not-supported-error (gfx:effect-texture effect))
      (signals xna:cna-not-supported-error (setf (gfx:effect-texture effect) nil))
      ;; And the three light views, whose graph build a content-published effect
      ;; never runs -- so without this they answered an AREF index error about a
      ;; private slot rather than saying what was wrong.
      (signals xna:cna-not-supported-error (gfx:directional-light-0 effect))
      (signals xna:cna-not-supported-error (gfx:directional-light-1 effect))
      (signals xna:cna-not-supported-error (gfx:directional-light-2 effect))
      (dolist (probe (list (lambda () (gfx:effect-techniques effect))
                           (lambda () (gfx:effect-texture effect))
                           (lambda () (gfx:directional-light-0 effect))))
        (handler-case (funcall probe)
          (xna:cna-not-supported-error (condition)
            (is (search "ContentManager.Load<Model>" (princ-to-string condition))
                "the refusal must name where the handle came from")
            (is (search "model-mesh-part-effect" (princ-to-string condition))
                "and the remedy"))))
      ;; And the 300 routes that do not read adapter state answer normally.
      (finishes (gfx:effect-world effect))
      (finishes (gfx:effect-view effect))
      (finishes (gfx:effect-vertex-color-enabled effect)))))

(define-native-test assigning-your-own-effect-repairs-the-part-and-the-collection
  "The remedy the refusal names, measured end to end.

`ModelMeshPart.set_Effect' in the pinned assembly walks the siblings and
maintains its mesh's `Effects': it removes the old effect only when no other part
still uses it and adds the new one only when no other part has it already. CNA's
`SetPartEffect' runs the same walk over its own collection, so the two must agree
-- and the replaced effect has adapter state, so its graph works again."
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (mesh (gfx:collection-item (gfx:model-meshes model) 0))
           (part (gfx:collection-item (gfx:model-mesh-parts mesh) 0))
           (published (gfx:model-mesh-part-effect part)))
      (is (= 1 (gfx:collection-count (gfx:model-mesh-effects mesh))))
      (let ((mine (own-effect game)))
        (is (typep mine 'gfx:basic-effect) "the fixture game makes one in LoadContent")
        (setf (gfx:model-mesh-part-effect part) mine)
        (is (eq mine (gfx:model-mesh-part-effect part)))
        (is (not (eq published (gfx:model-mesh-part-effect part))))
        (is (= 1 (gfx:collection-count (gfx:model-mesh-effects mesh)))
            "the old effect left the collection and the new one joined it")
        (is (eq mine (gfx:collection-item (gfx:model-mesh-effects mesh) 0)))
        ;; And the replaced effect answers for its own graph.
        (is (plusp (gfx:collection-count (gfx:effect-techniques mine))))
        (finishes (gfx:effect-current-technique mine))))))

;;; --- NATIVE: ownership ------------------------------------------------------

(define-native-test a-model-is-not-disposable-through-its-parts
  "None of ModelBone, ModelMesh or ModelMeshPart is IDisposable in XNA, and none
is here. The model releases them, and Unload releases the model."
  (with-model-game (game)
    (let* ((model (loaded-model game))
           (bone (gfx:collection-item (gfx:model-bones model) 0))
           (mesh (gfx:collection-item (gfx:model-meshes model) 0))
           (part (gfx:collection-item (gfx:model-mesh-parts mesh) 0)))
      (dolist (view (list bone mesh part))
        (signals xna:cna-usage-error (xna:dispose view))
        (is (not (xna:disposed-p view))
            "~a must still be usable after a refused disposal" (type-of view))))))

(define-native-test a-model-load-that-fails-leaves-the-game-owning-nothing
  "One asset load is one transaction, and a name nothing resolves is the cheapest
way to prove the failing half."
  (let ((game (make-instance 'model-game)))
    (unwind-protect
         (when (model-loading-available-p)
           (xna:run-one-frame game)
           (is (null (model-load-error game)))
           (let ((before (length (int:children-of game))))
             (signals xna:cna-error
               (xna.content:load-asset (xna:content game) 'gfx:model "no-such-model"))
             (is (= before (length (int:children-of game)))
                 "a failed load must add no child")))
      (is (%tear-down-model-game game)))))

;;; --- SOFTWARE_PIXEL: does a model's geometry reach the back buffer? ---------
;;;
;;; The level nothing above reaches. Every test up to here proves that routes
;;; succeeded, that handles resolve and that the graph is the fixture's; none of
;;; them says a triangle was ever rasterised. This does, on the same terms the
;;; primitive proof already does:
;;;
;;;   * the fixture's vertices **are** clip-space coordinates, so World, View and
;;;     Projection stay at their identity defaults and no matrix setter -- and
;;;     therefore no optional shim -- is involved. That matters: DRAW-MODEL sets
;;;     all three and would need one, and the rasterizer lane has none;
;;;   * the two triangles are on opposite halves of the screen and are **two
;;;     different colours**, so a pixel says which mesh drew it. A single-colour
;;;     fixture could not tell "both meshes drew" from "one mesh drew twice";
;;;   * `vertexColorEnabled` is set in the `.cnj`, so the colour is the vertex
;;;     colour rather than a shading result;
;;;   * every sampled point is well away from an edge, where a rasteriser's fill
;;;     rule is entitled to differ.
;;;
;;; **The effect is replaced first, and that is the CNA defect and not a
;;; shortcut.** A model still carrying the effect its loader published cannot be
;;; drawn at all: `cna_effect_get_techniques' on such a handle is a memory fault.
;;; Replacing it is the remedy the refusal names, it is an ordinary XNA idiom,
;;; and doing it here is what makes this a proof about *geometry* rather than
;;; about a CNA bug.

(defclass model-pixel-game (model-game)
  ((samples :initform nil :accessor samples)
   (sample-error :initform nil :accessor sample-error)
   (sampled :initform nil :accessor sampled)))

(defmethod xna:draw ((game model-pixel-game) game-time)
  (declare (ignore game-time))
  (incf (draws game))
  (unless (or (sampled game) (model-load-error game))
    (setf (sampled game) t)
    (handler-case
        (let ((device (xna:graphics-device game))
              (model (loaded-model game))
              (effect (own-effect game)))
          (gfx:clear device (xna:cornflower-blue))
          (setf (gfx:effect-vertex-color-enabled effect) t
                (gfx:effect-lighting-enabled effect) nil)
          (dolist (mesh (gfx:collection-elements (gfx:model-meshes model)))
            (setf (gfx:model-mesh-part-effect
                   (gfx:collection-item (gfx:model-mesh-parts mesh) 0))
                  effect)
            (gfx:draw-model-mesh mesh))
          (let* ((viewport (gfx:viewport device))
                 (width (gfx:viewport-width viewport))
                 (pixels (gfx:get-back-buffer-data device)))
            (setf (samples game) (lambda (x y) (aref pixels (+ x (* y width)))))))
      (error (condition) (setf (sample-error game) condition)))))

(define-native-test a-models-geometry-reaches-the-back-buffer
  "ModelMesh.Draw, with pixels.

`ModelMeshPart.Draw' is `assembly' in XNA and this binding reproduces it out of
SET-VERTEX-BUFFER, `(setf INDICES)' and DRAW-INDEXED-PRIMITIVES. That the three
calls succeed says nothing about rasterisation; this is what says the buffers a
loaded model owns actually feed the pipeline."
  (let ((game (make-instance 'model-pixel-game :exit-after 2)))
    (unwind-protect
         (block %pixel-body
           (xna:run game)
           (unless (model-loading-available-p)
             (%assert-model-loading-refused game)
             (return-from %pixel-body))
           (is (null (model-load-error game))
               "loading the model fixture failed: ~a" (model-load-error game))
           (is (sampled game) "the draw callback never ran")
           (let ((renderer (renderer game)))
             (if (not (rasterizing-renderer-p renderer))
                 (progn
                   (is (null (samples game))
                       "~a has no back-buffer readback but answered pixels" renderer)
                   (is (typep (sample-error game) 'xna:cna-not-supported-error)
                       "~a should refuse the readback with CNA-NOT-SUPPORTED-ERROR; ~
                        it signalled ~a" renderer (type-of (sample-error game))))
                 (progn
                   (when (sample-error game) (error (sample-error game)))
                   (let ((orange (xna:make-color 255 128 0 255))
                         (green (xna:make-color 0 255 128 255))
                         (background (xna:cornflower-blue)))
                     (flet ((at (x y) (funcall (samples game) x y)))
                       ;; The left mesh's own colour, well inside its triangle.
                       (dolist (point '((200 300) (150 350) (250 350)))
                         (is (xna:color-equal orange (at (first point) (second point)))
                             "(~d,~d) should be the LeftTriangle mesh's orange; it is ~a"
                             (first point) (second point)
                             (pixel-list (at (first point) (second point)))))
                       ;; The right mesh's own colour, which is what says both
                       ;; meshes drew and that neither drew the other's pixels.
                       (dolist (point '((600 300) (550 350) (650 350)))
                         (is (xna:color-equal green (at (first point) (second point)))
                             "(~d,~d) should be the RightTriangle mesh's green; it is ~a"
                             (first point) (second point)
                             (pixel-list (at (first point) (second point)))))
                       ;; Between them, above them and far away: still the clear
                       ;; colour, so a draw that covered the target would fail.
                       (dolist (point '((400 240) (400 60) (0 0) (200 460)))
                         (is (xna:color-equal background
                                              (at (first point) (second point)))
                             "(~d,~d) should still be the CornflowerBlue that was ~
                              cleared; it is ~a"
                             (first point) (second point)
                             (pixel-list (at (first point) (second point)))))
                       (note-rasterization
                        :model "~a: a Model loaded through ContentManager.Load<Model> ~
                                drew through ModelMesh.Draw, and each of its two meshes ~
                                put its own colour on the pixels its own triangle ~
                                covers and on none of the other's"
                        renderer)))))))
      (is (%tear-down-model-game game)))))
