;;;; packed-vector.lisp --- Microsoft.Xna.Framework.Graphics.PackedVector.
;;;;
;;;; Seventeen value types, each one packed integer with a documented bit
;;;; layout, and a way in and out of the vector types. Read from the pinned XNA
;;;; 4.0 Windows IL, where all of them go through two private helpers -- PackUtils
;;;; and, for the three half-precision types, HalfUtils -- and the helpers are
;;;; where the behaviour lives:
;;;;
;;;;   * every conversion rounds with `Math.Round(double)', which rounds **halves
;;;;     to even**, so the boundary values do not go the way a `floor(x + 0.5)'
;;;;     implementation sends them;
;;;;   * in PackUtils a NaN packs to zero and the infinities pack to the ends of
;;;;     the range, rather than propagating or signalling;
;;;;   * a signed normalised format reserves its most negative code point: the
;;;;     bit pattern that would mean -1.0 - 1ulp is read back as exactly -1.0,
;;;;     which is why a round trip through NormalizedByte4 is not the identity on
;;;;     that one value;
;;;;   * and XNA's 16-bit half is **not IEEE 754 binary16**. It has no infinity
;;;;     and no NaN: an exponent of 31 means 2^16 rather than a special value, so
;;;;     the largest pattern reads back as **131008.0** where binary16's largest
;;;;     finite value is 65504. Everything too large -- and an infinity, and a
;;;;     NaN -- saturates to that pattern. Half of the format's top exponent is
;;;;     spent on ordinary numbers instead of on the special values, and any code
;;;;     that treats these sixteen bits as binary16 will read them wrong.
;;;;
;;;; The seventeen types are generated by one macro from a table of bit fields,
;;;; because they differ in nothing else and a hand-written family of seventeen
;;;; near-identical structures is a place for one of them to drift.

(in-package #:microsoft.xna.framework.graphics.packed-vector)

;;; --- PackUtils --------------------------------------------------------------

(defmacro %fp (&body body)
  `(cna-lisp.internal:with-binary32-semantics ,@body))

(defun %clamp-and-round (value minimum maximum)
  "PackUtils.ClampAndRound.

A NaN answers zero, the infinities answer the ends of the range, and everything
else is clamped and then rounded by `Math.Round(double)' -- half to even."
  (%fp
    (cond ((cna-lisp.internal:nan-p value) 0)
          ((cna-lisp.internal:infinity-p value) (if (plusp value) maximum minimum))
          ((< value minimum) minimum)
          ((> value maximum) maximum)
          (t (round (float value 1.0d0))))))

(defun %pack-unsigned (bitmask value)
  "PackUtils.PackUnsigned: clamp into [0, BITMASK] and round. No scaling."
  (%clamp-and-round (xna::f value) 0 bitmask))

(defun %pack-signed (bitmask value)
  "PackUtils.PackSigned: clamp into the two's-complement range BITMASK spans."
  (%fp
    (let* ((maximum (float (ash bitmask -1) 1.0f0))
           (minimum (- (- maximum) 1.0f0)))
      (logand (%clamp-and-round (xna::f value) (round minimum) (round maximum)) bitmask))))

(defun %pack-unorm (bitmask value)
  "PackUtils.PackUNorm: scale a unit float by BITMASK, then clamp and round."
  (%fp (%clamp-and-round (* (xna::f value) (float bitmask 1.0f0)) 0 bitmask)))

(defun %unpack-unorm (bitmask value)
  "PackUtils.UnpackUNorm."
  (%fp (/ (float (logand value bitmask) 1.0f0) (float bitmask 1.0f0))))

(defun %pack-snorm (bitmask value)
  "PackUtils.PackSNorm: scale by half the range, then clamp and round."
  (%fp
    (let ((maximum (float (ash bitmask -1) 1.0f0)))
      (logand (%clamp-and-round (* (xna::f value) maximum)
                                (round (- maximum)) (round maximum))
              bitmask))))

(defun %unpack-snorm (bitmask value)
  "PackUtils.UnpackSNorm.

The most negative code point is spent on exactly -1.0: the pattern whose sign bit
is set and whose remaining bits are all zero reads back as -1.0 rather than as
the value one step below it, so packing -1.0 and unpacking it is a fixed point
while the neighbouring pattern is not reachable by packing at all."
  (%fp
    (let ((sign-bit (ash (1+ bitmask) -1)))
      (if (logtest value sign-bit)
          (if (= (logand value bitmask) sign-bit)
              -1.0f0
              (let* ((extended (logior value (lognot bitmask)))
                     (signed (- (logand extended #xFFFFFFFF) (ash 1 32))))
                (/ (float signed 1.0f0) (float (ash bitmask -1) 1.0f0))))
          (/ (float (logand value bitmask) 1.0f0) (float (ash bitmask -1) 1.0f0))))))

;;; --- HalfUtils --------------------------------------------------------------

(defun %half-pack (value)
  "HalfUtils.Pack: binary32 to XNA's 16-bit half.

Not IEEE 754 binary16: there is no infinity and no NaN. Anything whose binary32
pattern exceeds 0x47ffefff -- 131039.99 -- becomes 0x7fff with the original sign,
and so do the infinities and the NaNs; %HALF-UNPACK reads that back as 131008.
Values a little below the threshold reach the same pattern by rounding."
  (%fp
    (let* ((bits (cna-lisp.internal:single-float-bits value))
           (sign (ash (logand bits #x80000000) -16))
           (rest (logand bits #x7FFFFFFF)))
      (cond
        ((> rest #x47FFEFFF) (logand (logior sign #x7FFF) #xFFFF))
        ((< rest #x38800000)
         ;; Subnormal in the half format: shift the implied leading one down.
         (let* ((fraction (logior (logand rest #x7FFFFF) #x800000))
                (shift (- 113 (ash rest -23)))
                (shifted (if (<= shift 31) (ash fraction (- (logand shift 31))) 0)))
           (logand (logior sign
                           (ash (+ shifted #xFFF (logand (ash shifted -13) 1)) -13))
                   #xFFFF)))
        (t
         (let ((biased (logand (+ rest #xC8000000) #xFFFFFFFF)))
           (logand (logior sign
                           (ash (+ biased #xFFF (logand (ash rest -13) 1)) -13))
                   #xFFFF)))))))

(defun %half-unpack (value)
  "HalfUtils.Unpack: XNA's 16-bit half to binary32.

An exponent of 31 is not read as an infinity: it becomes 2^16 times the
mantissa, so the largest half pattern unpacks to 131008.0."
  (%fp
    (cna-lisp.internal:bits-single-float
     (if (zerop (logand value #x7C00))
         (if (zerop (logand value #x3FF))
             (ash (logand value #x8000) 16)
             (let ((exponent -14)
                   (mantissa (logand value #x3FF)))
               (loop until (logtest mantissa #x400)
                     do (decf exponent) (setf mantissa (ash mantissa 1)))
               (setf mantissa (logand mantissa (lognot #x400)))
               (logior (ash (logand value #x8000) 16)
                       (ash (+ exponent 127) 23)
                       (ash mantissa 13))))
         (logior (ash (logand value #x8000) 16)
                 (ash (+ (- (logand (ash value -10) 31) 15) 127) 23)
                 (ash (logand value #x3FF) 13))))))

;;; --- the generator ----------------------------------------------------------

(defun %sign-extend (value bits)
  "VALUE, BITS wide, read as a two's-complement integer."
  (if (logbitp (1- bits) value) (- value (ash 1 bits)) value))

(defmacro define-packed-vector (name width converter result &body fields)
  "Define one packed-vector value type.

NAME is the Lisp type; WIDTH is the packed integer's width in bits; CONVERTER is
the public conversion the contract gives this type and RESULT is what it answers.
Each field is (KIND MASK SHIFT), in the order X, Y, Z, W, where KIND says which
PackUtils pair the component goes through.

Every type with more than one component also gets a MAKE-<NAME>-FROM-VECTOR for
XNA's vector constructor, named rather than folded into MAKE-<NAME> for the same
reason MAKE-PLANE-FROM-VECTOR4 is named: one function that took either four
floats or one vector would be telling two constructors apart by the run-time type
of an argument."
  (let* ((packed (intern (format nil "~a-PACKED-VALUE" (symbol-name name))))
         (maker (intern (format nil "MAKE-~a" (symbol-name name))))
         (internal-maker (intern (format nil "%MAKE-~a" (symbol-name name))))
         (equality (intern (format nil "~a-EQUAL" (symbol-name name))))
         (convert (intern (format nil "~a-~a" (symbol-name name) (symbol-name converter))))
         (arity (length fields))
         (arguments (subseq '(x y z w) 0 arity)))
    (flet ((pack-form (field argument)
             (destructuring-bind (kind mask shift) field
               `(ash ,(ecase kind
                        (:unorm `(%pack-unorm ,mask ,argument))
                        (:snorm `(%pack-snorm ,mask ,argument))
                        (:unsigned `(%pack-unsigned ,mask ,argument))
                        (:signed `(%pack-signed ,mask ,argument))
                        (:half `(%half-pack ,argument)))
                     ,shift)))
           (unpack-form (field value)
             (destructuring-bind (kind mask shift) field
               (let ((shifted `(ash ,value ,(- shift))))
                 (ecase kind
                   (:unorm `(%unpack-unorm ,mask ,shifted))
                   (:snorm `(%unpack-snorm ,mask ,shifted))
                   (:unsigned `(float (logand ,shifted ,mask) 1.0f0))
                   (:signed `(float (%sign-extend (logand ,shifted ,mask)
                                                  ,(integer-length mask))
                                    1.0f0))
                   (:half `(%half-unpack (logand ,shifted #xFFFF))))))))
      `(progn
         (defstruct (,name (:constructor ,internal-maker (packed-value))
                           (:copier ,(intern (format nil "COPY-~a" (symbol-name name)))))
           ,(format nil "Microsoft.Xna.Framework.Graphics.PackedVector.~a: ~d bits."
                    (symbol-name name) width)
           (packed-value 0 :type (unsigned-byte ,width)))
         (defun ,maker (,@arguments)
           ,(format nil "~a(~{~a~^, ~}) and its vector constructor, which packs the same way."
                    (symbol-name name) (mapcar #'symbol-name arguments))
           (%fp
             (,internal-maker
              (logior ,@(mapcar #'pack-form fields arguments)))))
         ,@(when (> arity 1)
             (let ((from-vector (intern (format nil "MAKE-~a-FROM-VECTOR"
                                                (symbol-name name))))
                   (reader (ecase result
                             (:vector2 'xna:vector2-x) (:vector3 'xna:vector3-x)
                             (:vector4 'xna:vector4-x)))
                   (readers (ecase result
                              (:vector2 '(xna:vector2-x xna:vector2-y))
                              (:vector3 '(xna:vector3-x xna:vector3-y xna:vector3-z))
                              (:vector4 '(xna:vector4-x xna:vector4-y xna:vector4-z
                                          xna:vector4-w)))))
               (declare (ignore reader))
               `((defun ,from-vector (vector)
                   ,(format nil "~a(~a)." (symbol-name name)
                            (ecase result (:vector2 "Vector2") (:vector3 "Vector3")
                                          (:vector4 "Vector4")))
                   (,maker ,@(mapcar (lambda (r) `(,r vector))
                                     (subseq readers 0 arity)))))))
         (defun ,convert (value)
           ,(format nil "~a.~a." (symbol-name name) (symbol-name converter))
           (%fp
             (let ((packed (,packed value)))
               (declare (ignorable packed))
               ,(let ((forms (mapcar (lambda (field) (unpack-form field 'packed)) fields)))
                  (ecase result
                    (:single (first forms))
                    (:vector2 `(xna:make-vector2 ,@forms))
                    (:vector3 `(xna:make-vector3 ,@forms))
                    (:vector4 `(xna:make-vector4 ,@forms)))))))
         (defun ,equality (left right)
           ,(format nil "~a.Equals and op_Equality: the packed values are equal."
                    (symbol-name name))
           (= (,packed left) (,packed right)))
         ',name))))

;;; --- the seventeen types ----------------------------------------------------
;;;
;;; Each row is the type's bit layout, in the order X, Y, Z, W. The masks and
;;; shifts are the assembly's; the component order is the assembly's too, which
;;; is why the three `Bgr'/`Bgra' types put X at the *top* of the word and Z at
;;; the bottom while everything else runs the other way.

(define-packed-vector alpha8 8 to-alpha :single
  (:unorm 255 0))

(define-packed-vector bgr565 16 to-vector3 :vector3
  (:unorm 31 11) (:unorm 63 5) (:unorm 31 0))

(define-packed-vector bgra4444 16 to-vector4 :vector4
  (:unorm 15 8) (:unorm 15 4) (:unorm 15 0) (:unorm 15 12))

(define-packed-vector bgra5551 16 to-vector4 :vector4
  (:unorm 31 10) (:unorm 31 5) (:unorm 31 0) (:unorm 1 15))

(define-packed-vector byte4 32 to-vector4 :vector4
  (:unsigned 255 0) (:unsigned 255 8) (:unsigned 255 16) (:unsigned 255 24))

(define-packed-vector half-single 16 to-single :single
  (:half #xFFFF 0))

(define-packed-vector half-vector2 32 to-vector2 :vector2
  (:half #xFFFF 0) (:half #xFFFF 16))

(define-packed-vector half-vector4 64 to-vector4 :vector4
  (:half #xFFFF 0) (:half #xFFFF 16) (:half #xFFFF 32) (:half #xFFFF 48))

(define-packed-vector normalized-byte2 16 to-vector2 :vector2
  (:snorm #xFF 0) (:snorm #xFF 8))

(define-packed-vector normalized-byte4 32 to-vector4 :vector4
  (:snorm #xFF 0) (:snorm #xFF 8) (:snorm #xFF 16) (:snorm #xFF 24))

(define-packed-vector normalized-short2 32 to-vector2 :vector2
  (:snorm #xFFFF 0) (:snorm #xFFFF 16))

(define-packed-vector normalized-short4 64 to-vector4 :vector4
  (:snorm #xFFFF 0) (:snorm #xFFFF 16) (:snorm #xFFFF 32) (:snorm #xFFFF 48))

(define-packed-vector rg32 32 to-vector2 :vector2
  (:unorm 65535 0) (:unorm 65535 16))

(define-packed-vector rgba1010102 32 to-vector4 :vector4
  (:unorm 1023 0) (:unorm 1023 10) (:unorm 1023 20) (:unorm 3 30))

(define-packed-vector rgba64 64 to-vector4 :vector4
  (:unorm 65535 0) (:unorm 65535 16) (:unorm 65535 32) (:unorm 65535 48))

(define-packed-vector short2 32 to-vector2 :vector2
  (:signed #xFFFF 0) (:signed #xFFFF 16))

(define-packed-vector short4 64 to-vector4 :vector4
  (:signed #xFFFF 0) (:signed #xFFFF 16) (:signed #xFFFF 32) (:signed #xFFFF 48))
