package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type contract struct {
	Types []contractType `json:"types"`
}

type contractType struct {
	Name    string   `json:"name"`
	Members []member `json:"members"`
}

type member struct {
	Kind  string          `json:"kind"`
	Name  string          `json:"name"`
	Value json.RawMessage `json:"value"`
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	data, err := os.ReadFile(filepath.Join(root, "tools/api_compat/reference/xna40-windows-runtime-contract.json"))
	if err != nil {
		panic(err)
	}
	var reference contract
	if err := json.Unmarshal(data, &reference); err != nil {
		panic(err)
	}
	var keys *contractType
	for i := range reference.Types {
		if reference.Types[i].Name == "Microsoft.Xna.Framework.Input.Keys" {
			keys = &reference.Types[i]
			break
		}
	}
	if keys == nil {
		panic("Keys is absent from pinned contract")
	}
	var source strings.Builder
	source.WriteString("// Code generated by go run ./tools/generate_keys; DO NOT EDIT.\n\n")
	source.WriteString("package input\n\n")
	source.WriteString("// Keys preserves the exact XNA Int32 key identities.\n")
	source.WriteString("type Keys int32\n\nconst (\n")
	for _, item := range keys.Members {
		if item.Kind != "field" || item.Name == "value__" {
			continue
		}
		value := strings.Trim(string(item.Value), "\"")
		fmt.Fprintf(&source, "\tKeys%s Keys = %s\n", item.Name, value)
	}
	source.WriteString(")\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		panic(err)
	}
	output := filepath.Join(root, "Microsoft/Xna/Framework/Input/keys_generated.go")
	if err := os.WriteFile(output, formatted, 0o644); err != nil {
		panic(err)
	}
}
