apply plugin: 'java'
apply plugin: 'org.wisepersist.gwt'

dependencies {
    implementation project(':game')
    implementation 'com.google.gwt:gwt-user:2.10.0'
    implementation 'com.google.gwt:gwt-dev:2.10.0'
}

gwt {
    gwtVersion = '2.10.0'
    modules = ['com.openeggbert.cna.template.HelloGame']
    
    compiler {
        strict = true
        disableCastChecking = true
    }
}

// Ensure resources are copied
task copyResources(type: Copy) {
    from project(':game').sourceSets.main.resources
    into "$buildDir/gwt/out/HelloGame"
}
