apply plugin: 'java'
apply plugin: 'org.teavm'

dependencies {
    implementation project(':game')
    implementation 'org.teavm:teavm-classlib:0.8.1'
    implementation 'org.teavm:teavm-jso:0.8.1'
    implementation 'org.teavm:teavm-jso-apis:0.8.1'
}

teavm {
    mainClass = 'com.openeggbert.cna.template.teavm.TeaVMLauncher'
    targetDirectory = file("$buildDir/dist/js")
}

// Copy resources from game to build directory
task copyResources(type: Copy) {
    from project(':game').sourceSets.main.resources
    into "$buildDir/dist/js"
}

assemble.dependsPrefix 'teavm'
assemble.dependsOn copyResources
