//! Audited engine-layer calls over the canonical CNA ABI table.
//!
//! CNA's engine layer is a build-time choice, so every route here exists in the
//! exported ABI whether or not the layer was compiled in: a library without it
//! answers `NOT_SUPPORTED` rather than failing to resolve. Resolving the whole
//! table at load is still what this module does, because a *missing* symbol is
//! a different fact from a present one that refuses, and only the first should
//! stop the library from loading at all.

use cna_sys as sys;

use crate::error::Result;

use super::loader::NativeSource;
use super::Native;

/// Every reviewed engine-layer route, resolved once when the tables are filled.
#[derive(Debug)]
pub(crate) struct EngineApi {
    pub(crate) debug_draw_add_bounding_sphere: sys::cna_debug_draw_add_bounding_sphere_fn,
    pub(crate) debug_draw_add_box: sys::cna_debug_draw_add_box_fn,
    pub(crate) debug_draw_add_cross: sys::cna_debug_draw_add_cross_fn,
    pub(crate) debug_draw_add_frustum: sys::cna_debug_draw_add_frustum_fn,
    pub(crate) debug_draw_add_line: sys::cna_debug_draw_add_line_fn,
    pub(crate) debug_draw_add_sphere: sys::cna_debug_draw_add_sphere_fn,
    pub(crate) debug_draw_begin: sys::cna_debug_draw_begin_fn,
    pub(crate) debug_draw_clear: sys::cna_debug_draw_clear_fn,
    pub(crate) debug_draw_copy_vertices: sys::cna_debug_draw_copy_vertices_fn,
    pub(crate) debug_draw_create: sys::cna_debug_draw_create_fn,
    pub(crate) debug_draw_destroy: sys::cna_debug_draw_destroy_fn,
    pub(crate) debug_draw_end: sys::cna_debug_draw_end_fn,
    pub(crate) debug_draw_get_line_count: sys::cna_debug_draw_get_line_count_fn,
    pub(crate) debug_draw_is_depth_tested: sys::cna_debug_draw_is_depth_tested_fn,
    pub(crate) debug_draw_set_depth_tested: sys::cna_debug_draw_set_depth_tested_fn,
    pub(crate) indirect_draw_arguments_init: sys::cna_indirect_draw_arguments_init_fn,
    pub(crate) indirect_draw_indexed_arguments_init: sys::cna_indirect_draw_indexed_arguments_init_fn,
    pub(crate) model_mesh_part_get_morph_target_data_ext: sys::cna_model_mesh_part_get_morph_target_data_ext_fn,
    pub(crate) model_mesh_part_set_morph_target_data_ext: sys::cna_model_mesh_part_set_morph_target_data_ext_fn,
    pub(crate) model_mesh_part_set_morph_weights_ext: sys::cna_model_mesh_part_set_morph_weights_ext_fn,
    pub(crate) morph_target_data_ext_blend: sys::cna_morph_target_data_ext_blend_fn,
    pub(crate) morph_target_data_ext_copy_base_vertex_bytes: sys::cna_morph_target_data_ext_copy_base_vertex_bytes_fn,
    pub(crate) morph_target_data_ext_copy_normal_deltas: sys::cna_morph_target_data_ext_copy_normal_deltas_fn,
    pub(crate) morph_target_data_ext_copy_position_deltas: sys::cna_morph_target_data_ext_copy_position_deltas_fn,
    pub(crate) morph_target_data_ext_copy_tangent_deltas: sys::cna_morph_target_data_ext_copy_tangent_deltas_fn,
    pub(crate) morph_target_data_ext_copy_triangle_indices_ext: sys::cna_morph_target_data_ext_copy_triangle_indices_ext_fn,
    pub(crate) morph_target_data_ext_copy_type_name: sys::cna_morph_target_data_ext_copy_type_name_fn,
    pub(crate) morph_target_data_ext_copy_weight_keyframe: sys::cna_morph_target_data_ext_copy_weight_keyframe_fn,
    pub(crate) morph_target_data_ext_copy_weights: sys::cna_morph_target_data_ext_copy_weights_fn,
    pub(crate) morph_target_data_ext_create: sys::cna_morph_target_data_ext_create_fn,
    pub(crate) morph_target_data_ext_destroy: sys::cna_morph_target_data_ext_destroy_fn,
    pub(crate) morph_target_data_ext_get_base_vertex_byte_count: sys::cna_morph_target_data_ext_get_base_vertex_byte_count_fn,
    pub(crate) morph_target_data_ext_get_recompute_flat_normals_ext: sys::cna_morph_target_data_ext_get_recompute_flat_normals_ext_fn,
    pub(crate) morph_target_data_ext_get_stride: sys::cna_morph_target_data_ext_get_stride_fn,
    pub(crate) morph_target_data_ext_get_target_count: sys::cna_morph_target_data_ext_get_target_count_fn,
    pub(crate) morph_target_data_ext_get_type_name_byte_count: sys::cna_morph_target_data_ext_get_type_name_byte_count_fn,
    pub(crate) morph_target_data_ext_get_weight_track_info: sys::cna_morph_target_data_ext_get_weight_track_info_fn,
    pub(crate) morph_target_data_ext_set_recompute_flat_normals_ext: sys::cna_morph_target_data_ext_set_recompute_flat_normals_ext_fn,
    pub(crate) morph_target_data_ext_set_tangent_deltas: sys::cna_morph_target_data_ext_set_tangent_deltas_fn,
    pub(crate) morph_target_data_ext_set_triangle_indices_ext: sys::cna_morph_target_data_ext_set_triangle_indices_ext_fn,
    pub(crate) morph_target_data_ext_set_weight_track: sys::cna_morph_target_data_ext_set_weight_track_fn,
    pub(crate) morph_target_data_ext_set_weights: sys::cna_morph_target_data_ext_set_weights_fn,
    pub(crate) morph_weight_track_ext_evaluate: sys::cna_morph_weight_track_ext_evaluate_fn,
    pub(crate) matrix_create_infinite_perspective_field_of_view_ext: sys::cna_matrix_create_infinite_perspective_field_of_view_ext_fn,
    pub(crate) model_animations_ext_copy_clip_name_at: sys::cna_model_animations_ext_copy_clip_name_at_fn,
    pub(crate) model_animations_ext_copy_type_name: sys::cna_model_animations_ext_copy_type_name_fn,
    pub(crate) model_animations_ext_create: sys::cna_model_animations_ext_create_fn,
    pub(crate) model_animations_ext_destroy: sys::cna_model_animations_ext_destroy_fn,
    pub(crate) model_animations_ext_get_clip_count: sys::cna_model_animations_ext_get_clip_count_fn,
    pub(crate) model_animations_ext_get_clip_info_at: sys::cna_model_animations_ext_get_clip_info_at_fn,
    pub(crate) model_animations_ext_get_clip_name_byte_count_at: sys::cna_model_animations_ext_get_clip_name_byte_count_at_fn,
    pub(crate) model_animations_ext_get_type_name_byte_count: sys::cna_model_animations_ext_get_type_name_byte_count_fn,
    pub(crate) model_animations_ext_set_clip_target_space_at: sys::cna_model_animations_ext_set_clip_target_space_at_fn,
    pub(crate) model_mesh_part_get_sampler_state_ext: sys::cna_model_mesh_part_get_sampler_state_ext_fn,
    pub(crate) model_mesh_part_set_sampler_state_ext: sys::cna_model_mesh_part_set_sampler_state_ext_fn,
    #[allow(dead_code)]
    pub(crate) camera_copy_name_at_ext: sys::cna_camera_copy_name_at_ext_fn,
    /// The camera family is resolved in full but mostly unwrapped:
    /// `RUST-UPSTREAM-020` makes its teardown fault, so only the routes the
    /// reproducer drives have a safe API. The slots are still filled, because
    /// a library missing one should fail at load rather than at first use.
    #[allow(dead_code)]
    pub(crate) camera_create: sys::cna_camera_create_fn,
    pub(crate) camera_create_with_test_backend_ext: sys::cna_camera_create_with_test_backend_ext_fn,
    pub(crate) camera_destroy: sys::cna_camera_destroy_fn,
    #[allow(dead_code)]
    pub(crate) camera_device_info_init: sys::cna_camera_device_info_init_fn,
    pub(crate) camera_get_count_ext: sys::cna_camera_get_count_ext_fn,
    #[allow(dead_code)]
    pub(crate) camera_get_frame_height_ext: sys::cna_camera_get_frame_height_ext_fn,
    #[allow(dead_code)]
    pub(crate) camera_get_frame_width_ext: sys::cna_camera_get_frame_width_ext_fn,
    #[allow(dead_code)]
    pub(crate) camera_get_info_at_ext: sys::cna_camera_get_info_at_ext_fn,
    pub(crate) camera_get_is_supported_ext: sys::cna_camera_get_is_supported_ext_fn,
    #[allow(dead_code)]
    pub(crate) camera_get_name_size_at_ext: sys::cna_camera_get_name_size_at_ext_fn,
    pub(crate) camera_get_state_ext: sys::cna_camera_get_state_ext_fn,
    #[allow(dead_code)]
    pub(crate) camera_set_test_frame_ext: sys::cna_camera_set_test_frame_ext_fn,
    pub(crate) camera_set_test_state_ext: sys::cna_camera_set_test_state_ext_fn,
    #[allow(dead_code)]
    pub(crate) camera_try_acquire_frame_ext: sys::cna_camera_try_acquire_frame_ext_fn,
    pub(crate) model_mesh_part_create: sys::cna_model_mesh_part_create_fn,
    pub(crate) model_mesh_part_destroy: sys::cna_model_mesh_part_destroy_fn,
    pub(crate) model_mesh_part_get_num_vertices: sys::cna_model_mesh_part_get_num_vertices_fn,
    pub(crate) model_mesh_part_get_primitive_count: sys::cna_model_mesh_part_get_primitive_count_fn,
    pub(crate) model_mesh_part_get_primitive_type_ext: sys::cna_model_mesh_part_get_primitive_type_ext_fn,
    pub(crate) model_mesh_part_get_start_index: sys::cna_model_mesh_part_get_start_index_fn,
    pub(crate) model_mesh_part_get_vertex_offset: sys::cna_model_mesh_part_get_vertex_offset_fn,
    pub(crate) model_mesh_part_set_primitive_type_ext: sys::cna_model_mesh_part_set_primitive_type_ext_fn,
    pub(crate) image_based_light_ext_init: sys::cna_image_based_light_ext_init_fn,
    pub(crate) image_based_light_ext_is_valid: sys::cna_image_based_light_ext_is_valid_fn,
    pub(crate) animation_player_copy_bone_transforms: sys::cna_animation_player_copy_bone_transforms_fn,
    pub(crate) animation_player_copy_current_clip_name: sys::cna_animation_player_copy_current_clip_name_fn,
    pub(crate) animation_player_copy_skin_transforms: sys::cna_animation_player_copy_skin_transforms_fn,
    pub(crate) animation_player_copy_world_transforms: sys::cna_animation_player_copy_world_transforms_fn,
    pub(crate) animation_player_create: sys::cna_animation_player_create_fn,
    pub(crate) animation_player_destroy: sys::cna_animation_player_destroy_fn,
    pub(crate) animation_player_get_current_clip_info: sys::cna_animation_player_get_current_clip_info_fn,
    pub(crate) animation_player_get_current_clip_name_byte_count: sys::cna_animation_player_get_current_clip_name_byte_count_fn,
    pub(crate) animation_player_get_current_position: sys::cna_animation_player_get_current_position_fn,
    pub(crate) animation_player_start_clip: sys::cna_animation_player_start_clip_fn,
    pub(crate) animation_player_update: sys::cna_animation_player_update_fn,
    pub(crate) skinning_data_copy_bind_pose: sys::cna_skinning_data_copy_bind_pose_fn,
    pub(crate) skinning_data_copy_clip_name_at: sys::cna_skinning_data_copy_clip_name_at_fn,
    pub(crate) skinning_data_copy_clip_track: sys::cna_skinning_data_copy_clip_track_fn,
    pub(crate) skinning_data_copy_inverse_bind_pose: sys::cna_skinning_data_copy_inverse_bind_pose_fn,
    pub(crate) skinning_data_copy_skeleton_hierarchy: sys::cna_skinning_data_copy_skeleton_hierarchy_fn,
    pub(crate) skinning_data_copy_skeleton_root_name_ext: sys::cna_skinning_data_copy_skeleton_root_name_ext_fn,
    pub(crate) skinning_data_copy_skeleton_root_prefix: sys::cna_skinning_data_copy_skeleton_root_prefix_fn,
    pub(crate) skinning_data_copy_type_name: sys::cna_skinning_data_copy_type_name_fn,
    pub(crate) skinning_data_create: sys::cna_skinning_data_create_fn,
    pub(crate) skinning_data_destroy: sys::cna_skinning_data_destroy_fn,
    pub(crate) skinning_data_get_bone_count: sys::cna_skinning_data_get_bone_count_fn,
    pub(crate) skinning_data_get_clip_count: sys::cna_skinning_data_get_clip_count_fn,
    pub(crate) skinning_data_get_clip_info: sys::cna_skinning_data_get_clip_info_fn,
    pub(crate) skinning_data_get_clip_name_byte_count_at: sys::cna_skinning_data_get_clip_name_byte_count_at_fn,
    pub(crate) skinning_data_get_clip_target_space_ext: sys::cna_skinning_data_get_clip_target_space_ext_fn,
    pub(crate) skinning_data_get_skeleton_root_name_byte_count_ext: sys::cna_skinning_data_get_skeleton_root_name_byte_count_ext_fn,
    pub(crate) skinning_data_get_skeleton_root_node_index_ext: sys::cna_skinning_data_get_skeleton_root_node_index_ext_fn,
    pub(crate) skinning_data_get_type_name_byte_count: sys::cna_skinning_data_get_type_name_byte_count_fn,
    pub(crate) skinning_data_set_clip_target_space_ext: sys::cna_skinning_data_set_clip_target_space_ext_fn,
    pub(crate) skinning_data_set_skeleton_root_name_ext: sys::cna_skinning_data_set_skeleton_root_name_ext_fn,
    pub(crate) skinning_data_set_skeleton_root_node_index_ext: sys::cna_skinning_data_set_skeleton_root_node_index_ext_fn,
    pub(crate) skinned_model_ext_add_part: sys::cna_skinned_model_ext_add_part_fn,
    pub(crate) skinned_model_ext_attach_parts: sys::cna_skinned_model_ext_attach_parts_fn,
    pub(crate) skinned_model_ext_compute_bone_transforms: sys::cna_skinned_model_ext_compute_bone_transforms_fn,
    pub(crate) skinned_model_ext_copy_bind_pose_local: sys::cna_skinned_model_ext_copy_bind_pose_local_fn,
    pub(crate) skinned_model_ext_copy_clip_name_at: sys::cna_skinned_model_ext_copy_clip_name_at_fn,
    pub(crate) skinned_model_ext_copy_clip_track: sys::cna_skinned_model_ext_copy_clip_track_fn,
    pub(crate) skinned_model_ext_copy_inverse_bind_pose_global: sys::cna_skinned_model_ext_copy_inverse_bind_pose_global_fn,
    pub(crate) skinned_model_ext_copy_parent_bone_indices: sys::cna_skinned_model_ext_copy_parent_bone_indices_fn,
    pub(crate) skinned_model_ext_copy_part_name_at: sys::cna_skinned_model_ext_copy_part_name_at_fn,
    pub(crate) skinned_model_ext_create: sys::cna_skinned_model_ext_create_fn,
    pub(crate) skinned_model_ext_create_default: sys::cna_skinned_model_ext_create_default_fn,
    pub(crate) skinned_model_ext_create_move: sys::cna_skinned_model_ext_create_move_fn,
    pub(crate) skinned_model_ext_destroy: sys::cna_skinned_model_ext_destroy_fn,
    pub(crate) skinned_model_ext_get_bone_count: sys::cna_skinned_model_ext_get_bone_count_fn,
    pub(crate) skinned_model_ext_get_clip_count: sys::cna_skinned_model_ext_get_clip_count_fn,
    pub(crate) skinned_model_ext_get_clip_info: sys::cna_skinned_model_ext_get_clip_info_fn,
    pub(crate) skinned_model_ext_get_clip_name_byte_count_at: sys::cna_skinned_model_ext_get_clip_name_byte_count_at_fn,
    pub(crate) skinned_model_ext_get_owned_resource_counts: sys::cna_skinned_model_ext_get_owned_resource_counts_fn,
    pub(crate) skinned_model_ext_get_part_at: sys::cna_skinned_model_ext_get_part_at_fn,
    pub(crate) skinned_model_ext_get_part_count: sys::cna_skinned_model_ext_get_part_count_fn,
    pub(crate) skinned_model_ext_get_part_name_byte_count_at: sys::cna_skinned_model_ext_get_part_name_byte_count_at_fn,
    pub(crate) skinned_model_ext_move_assign: sys::cna_skinned_model_ext_move_assign_fn,
    pub(crate) skinned_model_ext_remove_clip: sys::cna_skinned_model_ext_remove_clip_fn,
    pub(crate) skinned_model_ext_remove_part: sys::cna_skinned_model_ext_remove_part_fn,
    pub(crate) skinned_model_ext_set_clip: sys::cna_skinned_model_ext_set_clip_fn,
    pub(crate) skinned_model_ext_set_skeleton: sys::cna_skinned_model_ext_set_skeleton_fn,
}

impl EngineApi {
    pub(super) fn load(source: &NativeSource) -> Result<Self> {
        macro_rules! symbol {
            ($name:ident, $ty:ty) => {
                super::loader::acquire!(source, $name, $ty)
            };
        }
        Ok(Self {
            debug_draw_add_bounding_sphere: symbol!(cna_debug_draw_add_bounding_sphere, _),
            debug_draw_add_box: symbol!(cna_debug_draw_add_box, _),
            debug_draw_add_cross: symbol!(cna_debug_draw_add_cross, _),
            debug_draw_add_frustum: symbol!(cna_debug_draw_add_frustum, _),
            debug_draw_add_line: symbol!(cna_debug_draw_add_line, _),
            debug_draw_add_sphere: symbol!(cna_debug_draw_add_sphere, _),
            debug_draw_begin: symbol!(cna_debug_draw_begin, _),
            debug_draw_clear: symbol!(cna_debug_draw_clear, _),
            debug_draw_copy_vertices: symbol!(cna_debug_draw_copy_vertices, _),
            debug_draw_create: symbol!(cna_debug_draw_create, _),
            debug_draw_destroy: symbol!(cna_debug_draw_destroy, _),
            debug_draw_end: symbol!(cna_debug_draw_end, _),
            debug_draw_get_line_count: symbol!(cna_debug_draw_get_line_count, _),
            debug_draw_is_depth_tested: symbol!(cna_debug_draw_is_depth_tested, _),
            debug_draw_set_depth_tested: symbol!(cna_debug_draw_set_depth_tested, _),
            indirect_draw_arguments_init: symbol!(cna_indirect_draw_arguments_init, _),
            indirect_draw_indexed_arguments_init: symbol!(cna_indirect_draw_indexed_arguments_init, _),
            model_mesh_part_get_morph_target_data_ext: symbol!(cna_model_mesh_part_get_morph_target_data_ext, _),
            model_mesh_part_set_morph_target_data_ext: symbol!(cna_model_mesh_part_set_morph_target_data_ext, _),
            model_mesh_part_set_morph_weights_ext: symbol!(cna_model_mesh_part_set_morph_weights_ext, _),
            morph_target_data_ext_blend: symbol!(cna_morph_target_data_ext_blend, _),
            morph_target_data_ext_copy_base_vertex_bytes: symbol!(cna_morph_target_data_ext_copy_base_vertex_bytes, _),
            morph_target_data_ext_copy_normal_deltas: symbol!(cna_morph_target_data_ext_copy_normal_deltas, _),
            morph_target_data_ext_copy_position_deltas: symbol!(cna_morph_target_data_ext_copy_position_deltas, _),
            morph_target_data_ext_copy_tangent_deltas: symbol!(cna_morph_target_data_ext_copy_tangent_deltas, _),
            morph_target_data_ext_copy_triangle_indices_ext: symbol!(cna_morph_target_data_ext_copy_triangle_indices_ext, _),
            morph_target_data_ext_copy_type_name: symbol!(cna_morph_target_data_ext_copy_type_name, _),
            morph_target_data_ext_copy_weight_keyframe: symbol!(cna_morph_target_data_ext_copy_weight_keyframe, _),
            morph_target_data_ext_copy_weights: symbol!(cna_morph_target_data_ext_copy_weights, _),
            morph_target_data_ext_create: symbol!(cna_morph_target_data_ext_create, _),
            morph_target_data_ext_destroy: symbol!(cna_morph_target_data_ext_destroy, _),
            morph_target_data_ext_get_base_vertex_byte_count: symbol!(cna_morph_target_data_ext_get_base_vertex_byte_count, _),
            morph_target_data_ext_get_recompute_flat_normals_ext: symbol!(cna_morph_target_data_ext_get_recompute_flat_normals_ext, _),
            morph_target_data_ext_get_stride: symbol!(cna_morph_target_data_ext_get_stride, _),
            morph_target_data_ext_get_target_count: symbol!(cna_morph_target_data_ext_get_target_count, _),
            morph_target_data_ext_get_type_name_byte_count: symbol!(cna_morph_target_data_ext_get_type_name_byte_count, _),
            morph_target_data_ext_get_weight_track_info: symbol!(cna_morph_target_data_ext_get_weight_track_info, _),
            morph_target_data_ext_set_recompute_flat_normals_ext: symbol!(cna_morph_target_data_ext_set_recompute_flat_normals_ext, _),
            morph_target_data_ext_set_tangent_deltas: symbol!(cna_morph_target_data_ext_set_tangent_deltas, _),
            morph_target_data_ext_set_triangle_indices_ext: symbol!(cna_morph_target_data_ext_set_triangle_indices_ext, _),
            morph_target_data_ext_set_weight_track: symbol!(cna_morph_target_data_ext_set_weight_track, _),
            morph_target_data_ext_set_weights: symbol!(cna_morph_target_data_ext_set_weights, _),
            morph_weight_track_ext_evaluate: symbol!(cna_morph_weight_track_ext_evaluate, _),
            matrix_create_infinite_perspective_field_of_view_ext: symbol!(cna_matrix_create_infinite_perspective_field_of_view_ext, _),
            model_animations_ext_copy_clip_name_at: symbol!(cna_model_animations_ext_copy_clip_name_at, _),
            model_animations_ext_copy_type_name: symbol!(cna_model_animations_ext_copy_type_name, _),
            model_animations_ext_create: symbol!(cna_model_animations_ext_create, _),
            model_animations_ext_destroy: symbol!(cna_model_animations_ext_destroy, _),
            model_animations_ext_get_clip_count: symbol!(cna_model_animations_ext_get_clip_count, _),
            model_animations_ext_get_clip_info_at: symbol!(cna_model_animations_ext_get_clip_info_at, _),
            model_animations_ext_get_clip_name_byte_count_at: symbol!(cna_model_animations_ext_get_clip_name_byte_count_at, _),
            model_animations_ext_get_type_name_byte_count: symbol!(cna_model_animations_ext_get_type_name_byte_count, _),
            model_animations_ext_set_clip_target_space_at: symbol!(cna_model_animations_ext_set_clip_target_space_at, _),
            model_mesh_part_get_sampler_state_ext: symbol!(cna_model_mesh_part_get_sampler_state_ext, _),
            model_mesh_part_set_sampler_state_ext: symbol!(cna_model_mesh_part_set_sampler_state_ext, _),
            camera_copy_name_at_ext: symbol!(cna_camera_copy_name_at_ext, _),
            camera_create: symbol!(cna_camera_create, _),
            camera_create_with_test_backend_ext: symbol!(cna_camera_create_with_test_backend_ext, _),
            camera_destroy: symbol!(cna_camera_destroy, _),
            camera_device_info_init: symbol!(cna_camera_device_info_init, _),
            camera_get_count_ext: symbol!(cna_camera_get_count_ext, _),
            camera_get_frame_height_ext: symbol!(cna_camera_get_frame_height_ext, _),
            camera_get_frame_width_ext: symbol!(cna_camera_get_frame_width_ext, _),
            camera_get_info_at_ext: symbol!(cna_camera_get_info_at_ext, _),
            camera_get_is_supported_ext: symbol!(cna_camera_get_is_supported_ext, _),
            camera_get_name_size_at_ext: symbol!(cna_camera_get_name_size_at_ext, _),
            camera_get_state_ext: symbol!(cna_camera_get_state_ext, _),
            camera_set_test_frame_ext: symbol!(cna_camera_set_test_frame_ext, _),
            camera_set_test_state_ext: symbol!(cna_camera_set_test_state_ext, _),
            camera_try_acquire_frame_ext: symbol!(cna_camera_try_acquire_frame_ext, _),
            model_mesh_part_create: symbol!(cna_model_mesh_part_create, _),
            model_mesh_part_destroy: symbol!(cna_model_mesh_part_destroy, _),
            model_mesh_part_get_num_vertices: symbol!(cna_model_mesh_part_get_num_vertices, _),
            model_mesh_part_get_primitive_count: symbol!(cna_model_mesh_part_get_primitive_count, _),
            model_mesh_part_get_primitive_type_ext: symbol!(cna_model_mesh_part_get_primitive_type_ext, _),
            model_mesh_part_get_start_index: symbol!(cna_model_mesh_part_get_start_index, _),
            model_mesh_part_get_vertex_offset: symbol!(cna_model_mesh_part_get_vertex_offset, _),
            model_mesh_part_set_primitive_type_ext: symbol!(cna_model_mesh_part_set_primitive_type_ext, _),
            image_based_light_ext_init: symbol!(cna_image_based_light_ext_init, _),
            image_based_light_ext_is_valid: symbol!(cna_image_based_light_ext_is_valid, _),
            animation_player_copy_bone_transforms: symbol!(cna_animation_player_copy_bone_transforms, _),
            animation_player_copy_current_clip_name: symbol!(cna_animation_player_copy_current_clip_name, _),
            animation_player_copy_skin_transforms: symbol!(cna_animation_player_copy_skin_transforms, _),
            animation_player_copy_world_transforms: symbol!(cna_animation_player_copy_world_transforms, _),
            animation_player_create: symbol!(cna_animation_player_create, _),
            animation_player_destroy: symbol!(cna_animation_player_destroy, _),
            animation_player_get_current_clip_info: symbol!(cna_animation_player_get_current_clip_info, _),
            animation_player_get_current_clip_name_byte_count: symbol!(cna_animation_player_get_current_clip_name_byte_count, _),
            animation_player_get_current_position: symbol!(cna_animation_player_get_current_position, _),
            animation_player_start_clip: symbol!(cna_animation_player_start_clip, _),
            animation_player_update: symbol!(cna_animation_player_update, _),
            skinning_data_copy_bind_pose: symbol!(cna_skinning_data_copy_bind_pose, _),
            skinning_data_copy_clip_name_at: symbol!(cna_skinning_data_copy_clip_name_at, _),
            skinning_data_copy_clip_track: symbol!(cna_skinning_data_copy_clip_track, _),
            skinning_data_copy_inverse_bind_pose: symbol!(cna_skinning_data_copy_inverse_bind_pose, _),
            skinning_data_copy_skeleton_hierarchy: symbol!(cna_skinning_data_copy_skeleton_hierarchy, _),
            skinning_data_copy_skeleton_root_name_ext: symbol!(cna_skinning_data_copy_skeleton_root_name_ext, _),
            skinning_data_copy_skeleton_root_prefix: symbol!(cna_skinning_data_copy_skeleton_root_prefix, _),
            skinning_data_copy_type_name: symbol!(cna_skinning_data_copy_type_name, _),
            skinning_data_create: symbol!(cna_skinning_data_create, _),
            skinning_data_destroy: symbol!(cna_skinning_data_destroy, _),
            skinning_data_get_bone_count: symbol!(cna_skinning_data_get_bone_count, _),
            skinning_data_get_clip_count: symbol!(cna_skinning_data_get_clip_count, _),
            skinning_data_get_clip_info: symbol!(cna_skinning_data_get_clip_info, _),
            skinning_data_get_clip_name_byte_count_at: symbol!(cna_skinning_data_get_clip_name_byte_count_at, _),
            skinning_data_get_clip_target_space_ext: symbol!(cna_skinning_data_get_clip_target_space_ext, _),
            skinning_data_get_skeleton_root_name_byte_count_ext: symbol!(cna_skinning_data_get_skeleton_root_name_byte_count_ext, _),
            skinning_data_get_skeleton_root_node_index_ext: symbol!(cna_skinning_data_get_skeleton_root_node_index_ext, _),
            skinning_data_get_type_name_byte_count: symbol!(cna_skinning_data_get_type_name_byte_count, _),
            skinning_data_set_clip_target_space_ext: symbol!(cna_skinning_data_set_clip_target_space_ext, _),
            skinning_data_set_skeleton_root_name_ext: symbol!(cna_skinning_data_set_skeleton_root_name_ext, _),
            skinning_data_set_skeleton_root_node_index_ext: symbol!(cna_skinning_data_set_skeleton_root_node_index_ext, _),
            skinned_model_ext_add_part: symbol!(cna_skinned_model_ext_add_part, _),
            skinned_model_ext_attach_parts: symbol!(cna_skinned_model_ext_attach_parts, _),
            skinned_model_ext_compute_bone_transforms: symbol!(cna_skinned_model_ext_compute_bone_transforms, _),
            skinned_model_ext_copy_bind_pose_local: symbol!(cna_skinned_model_ext_copy_bind_pose_local, _),
            skinned_model_ext_copy_clip_name_at: symbol!(cna_skinned_model_ext_copy_clip_name_at, _),
            skinned_model_ext_copy_clip_track: symbol!(cna_skinned_model_ext_copy_clip_track, _),
            skinned_model_ext_copy_inverse_bind_pose_global: symbol!(cna_skinned_model_ext_copy_inverse_bind_pose_global, _),
            skinned_model_ext_copy_parent_bone_indices: symbol!(cna_skinned_model_ext_copy_parent_bone_indices, _),
            skinned_model_ext_copy_part_name_at: symbol!(cna_skinned_model_ext_copy_part_name_at, _),
            skinned_model_ext_create: symbol!(cna_skinned_model_ext_create, _),
            skinned_model_ext_create_default: symbol!(cna_skinned_model_ext_create_default, _),
            skinned_model_ext_create_move: symbol!(cna_skinned_model_ext_create_move, _),
            skinned_model_ext_destroy: symbol!(cna_skinned_model_ext_destroy, _),
            skinned_model_ext_get_bone_count: symbol!(cna_skinned_model_ext_get_bone_count, _),
            skinned_model_ext_get_clip_count: symbol!(cna_skinned_model_ext_get_clip_count, _),
            skinned_model_ext_get_clip_info: symbol!(cna_skinned_model_ext_get_clip_info, _),
            skinned_model_ext_get_clip_name_byte_count_at: symbol!(cna_skinned_model_ext_get_clip_name_byte_count_at, _),
            skinned_model_ext_get_owned_resource_counts: symbol!(cna_skinned_model_ext_get_owned_resource_counts, _),
            skinned_model_ext_get_part_at: symbol!(cna_skinned_model_ext_get_part_at, _),
            skinned_model_ext_get_part_count: symbol!(cna_skinned_model_ext_get_part_count, _),
            skinned_model_ext_get_part_name_byte_count_at: symbol!(cna_skinned_model_ext_get_part_name_byte_count_at, _),
            skinned_model_ext_move_assign: symbol!(cna_skinned_model_ext_move_assign, _),
            skinned_model_ext_remove_clip: symbol!(cna_skinned_model_ext_remove_clip, _),
            skinned_model_ext_remove_part: symbol!(cna_skinned_model_ext_remove_part, _),
            skinned_model_ext_set_clip: symbol!(cna_skinned_model_ext_set_clip, _),
            skinned_model_ext_set_skeleton: symbol!(cna_skinned_model_ext_set_skeleton, _),
        })
    }
}

/// The last of `graphics_ext.h`.
impl Native {
    /// Draws the ASCII post-process effect over a source texture.
    ///
    /// The destination rectangle is optional: `None` covers the whole target,
    /// which is what a full-screen post-process wants and is why the route
    /// takes a pointer rather than a value.
    pub(crate) fn draw_ascii_post_process(
        &self,
        effect: sys::CNA_AsciiPostProcessEffectHandle,
        source: sys::CNA_Handle,
        destination: Option<&sys::CNA_Rectangle>,
    ) -> Result<()> {
        // SAFETY: both handles are live, and the rectangle -- when there is one
        // -- is a live borrow for the duration of the call.
        self.check(unsafe {
            (self.ascii_post_process_effect_draw)(
                effect,
                source,
                destination.map_or(core::ptr::null(), |value| value),
            )
        })
    }
}
